config/routes.rb
Rails.application.routes.draw do

  get 'comments/new'
  get 'topics/new'
  get 'sessions/new'
  # get 'users/new'

  root "pages#index"
  get 'pages/help'

  resources :users
  resources :topics


  get "favorites/index"

  # お気に入りの追加
  post "/favorites",to: "favorites#create"

  # お気に入りの削除
  delete "/favorites", to: "favorites#destroy"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #コメントの送信
  post "topics/comments", to: "comments#create"
  #コメントの削除
  delete "/comments", to:"comments#destroy"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :user
  belongs_to :topic

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: "user"

  #コメントテーブルとの関連
  has_many :comments

end

app/models/user.rb
class User < ApplicationRecord

  # 各フォームに値が入っているか確認
  validates :name,  presence: { message: "%{value} を入力してください" }
  validates :email, presence: { message: "%{value} を入力してください" }
  validates :password, presence: { message: "%{value} を入力してください" }

  #名前の文字数制限
  validates :name, length: { maximum: 15,message: "は15字以内にしてください" }

  #メールの形式に関する制限
  validates :email, format: { with: /[A-Za-z0-9._+]+@[A-Za-z]+.[A-Za-z]/,
    message: "は~ @ ~ . ~の表現にしてください" }

  #パスワードの文字数制限
  validates :password, length: { in: 8..32, too_long:"は３２文字以内にしてください", too_short:"は８文字以上にしてください"}

  validates :password, format: { with: /(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)/,
    message: "%{value}はアルファべット（大小）と半角数字の混合にしてください" }

  #パスワードが一致しているかの確認
  # validates :password, confirmation: true
  validates :password, confirmation: { message: "とpasswordの値が一致していません" }
  # validates :password_confirmation, presence: true

  has_secure_password
  #画像テーブル
  has_many :topics

  # お気に入りテーブル
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: "topic"

  # コメントテーブル
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger

  # extend ApplicationHelper

  helper_method :current_user, :logged_in?

  def current_user
    # @current_user が偽か未定義ならばUser~を代入
    @current_user ||=User.find_by(id: session[:user_id])

  end

  def logged_in?
    !current_user.nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new
    @comment[:body]=comment_params[:body]
    @comment[:user_id]=current_user.id
    @comment[:topic_id]=comment_params[:topic_id]

    if @comment.save
      redirect_to topics_path
    else
      redirect_to topics_path, danger: "コメント投稿失敗"
      # render :topic/index
    end
  end

  def destroy
    @comment=Comment.find(params[:id])
    @comment.destroy
    redirect_to topics_path
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :topic_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite=Favorite.new
    favorite.user_id=current_user.id
    favorite.topic_id=params[:topic_id]

    if favorite.save
      redirect_to topics_path, success: "お気に入りに登録しました"
    else
      redirect_to topics_path, danger: "お気に入りの登録に失敗しました"
    end
  end

  def destroy
    favorite=Favorite.find_by(user_id: current_user.id,topic_id: params[:topic_id])
    favorite.destroy
    redirect_to topics_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email_params)
    if @user && @user.authenticate(password_params[:password])
      log_in user
      # redirect_to root_path,success:"ログインに成功しました"
      redirect_to topics_path,success:"ログインに成功しました"
    else
      flash.now[:danger]="ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: "ログアウトしました"
  end

  private
  def log_in(user)
    session[:user_id]=user.id
  end

  # emailのstrong_params
  def email_params
    params.require(:session).permit(:email)
  end

  # passwordのstrong_params
  def password_params
    params.require(:session).permit(:password)
  end

  def log_out
    session.delete(:user_id)
    @current_user=nil
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all.includes(:favorite_users)
    #コメント一覧を表示するための設定
    @comments=Comment.all
    #topic/indexに反映させたい場合はここに記述する
    @comment=Comment.new
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path,success: "投稿に成功しました"
    else
      flash.now[:danger]="投稿に失敗しました"
      render :new
    end
  end

  # 削除機能の実装
  def destroy
    @topic =Topic.find(params[:id])
    # @topic =Topic.find(id: params[:id])
    @topic.destroy
    redirect_to topics_path,success: "画像を削除しました"
  end

  private
  def topic_params
    params.require(:topic).permit(:image,:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user= User.new
  end
  def create
    # binding.pry
    # @user=User.new(name: params[:user][:name],email: params[:user][:email])
    @user=User.new(user_params)

    if @user.save
      redirect_to root_path,success: "登録が完了しました"
    else
      flash.now[:danger]="登録に失敗しました"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # def current_user

  #   @current_user ||=User.find_by(id: session[:user_id])
  # end
  # def logged_in?
  #   !current_user.nil?
  # end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic|%>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag "icons/comment.png", class: "topic-index-icon"%>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>


  <body>
    <% flash.each do |key,value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">

        <%= link_to root_path do %>
          <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>

        <ul class="nav navbar-nav navbar-right">

          <% if logged_in? %>
            <!-- マイページに戻るリンクを追加 -->
            <li>
              <%= link_to topics_path do %>
                <%= image_tag "icons/my_img.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to favorites_index_path do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag "icons/camera.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path,method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>

  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you Happy</h1>
    <h2 class="text-white">Pictgram is a servise that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to "Sign in",new_user_path,class: "btn btn-block btn-white"%>
      </div>
      <div class="col-md-3">
        <%= link_to "Log in",login_path,class: "btn btn-block btn-white"%>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%=image_tag topic.image.url%>

            <!-- お気に入りに登録済み -->
            <% if topic.favorite_users.include?(current_user)%>

              <%= link_to favorites_path(topic_id: topic.id),method: :delete, remote: true do%>
                <%= image_tag "icons/red-heart.png",class: "topic-index-icon" %>
              <% end %>
              <!-- お気に入りの数を数える -->
              <p class="topic-text"><%=topic.favorite_users.count %></p>

            <!-- お気に入りに未登録-->
            <%else%>

              <%= link_to favorites_path(topic_id: topic.id),method: :post, remote: true do%>
                <%= image_tag "icons/heart-black.png",class: "topic-index-icon" %>
              <% end %>

              <!-- お気に入りの数を数える -->
              <p class="topic-text"><%= topic.favorite_users.count %></p>

            <% end %>

            <!-- 画像の削除 -->
            <%= link_to topic_path(topic),method: :delete do%>
              <%=image_tag "icons/delete.png",class: "topic-index-icon"%>
            <%end%>

            <!-- 画像の説明文章 -->
            <p class="topic-text">
              <%= topic.description %>
            </p>

            <!-- コメント一覧 -->
            <h4 class="">◎コメント一覧</h4>
            <% @comments.each do |comment| %>
              <% if comment[:topic_id]==topic.id%>
                <%= comment.body %>
                <!-- コメントの削除機能 -->
                <% if comment.user_id== current_user.id %>
                  <%= button_to "削除", { controller: "comments", :action => "destroy", :id => comment.id}, :method => :delete%>
                <% end %>
              <% end %>
            <% end %>

            <!-- コメント投稿欄 -->
            <%= form_for(:comment , url: topics_comments_path) do |f|%>
              <div class="form-group">
                <%= f.text_field :body,class: "form-control",style: "width:80%; height:30px; display:inline-block;"%>
                <input type="image" src="/assets/icons/comment.png" class="topic-index-icon">
                <%=f.hidden_field :topic_id, :value => topic.id %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f|%>
          <div class="form-group">
            <%=f.label :image%>
            <%=f.file_field :image%>
          </div>
          <div class="form-group">
            <%=f.label :description%>
            <%=f.text_area :description,class: "form-control"%>
          </div>
          <%=f.submit "投稿",class: "btn btn-black btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>

        <%= form_for @user do |f| %>
          <!-- 名前の入力フォーム -->
          <div class="form-group">
            <%= f.label :name, class: "text-white" %>
            <%= f.text_field :name, class: "form-control"%>
            <!-- エラーメッセージ -->
            <% if @user.errors.any? %>
              <% @user.errors.full_messages_for(:name).each do |message| %>
                <p class="text-white"><%= message %></p>
              <% end %>
            <% end %>
          </div>
          <!-- メールアドレスの入力フォーム -->
          <div class="form-group">
            <%= f.label :email, class: "text-white"%>
            <%= f.text_field :email, class: "form-control" %>
            <!-- エラーメッセージ -->
            <% if @user.errors.any? %>
              <% @user.errors.full_messages_for(:email).each do |message| %>
                <p class="text-white"><%= message %></p>
              <% end %>
            <% end %>
          </div>
          <!-- パスワードの入力フォーム -->
          <div class="form-group">
            <%= f.label :password, class: "text-white"%>
            <%= f.text_field :password, class: "form-control" %>
            <!-- エラーメッセージ -->
            <% if @user.errors.any? %>
              <% @user.errors.full_messages_for(:password).each do |message| %>
                <p class="text-white"><%= message %></p>
              <% end %>
            <% end %>
          </div>
          <!-- パスワードの確認フォーム -->
          <div class="form-group">
            <%= f.label :password_confirmation, class: "text-white"%>
            <%= f.text_field :password_confirmation, class: "form-control" %>
            <!-- エラーメッセージ -->
            <% if @user.errors.any? %>
              <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
                <p class="text-white"><%= message %></p>
              <% end %>
            <% end %>
          </div>
          <%= f.submit "登録", class: "btn-block btn-white"%>
        <% end %>
        <%= link_to "ログインはこちら",login_path,class: "text-white"%>
      </div>
    </div>
  </div>
</div>